include: package:lint/analysis_options.yaml

# linter:
#   rules:
#     - parameter_assignments


# can change the severity here: ignore, info, warning, error 
analyzer:
  errors:
    missing_required_param: error
    parameter_assignments: error
    missing_return: error
    must_be_immutable: warning
    prefer_const_constructors: ignore
    avoid_bool_literals_in_conditional_expressions: ignore
    avoid_setters_without_getters : ignore
